openapi: 3.0.0
info:
  version: "1.0"
  title: Dossier
  description: ""
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/FILIPKOWAL_1/Dossier/1.0

security:
  - OAuth2: []
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            arranger: Access to /invite and /reject endpoints

paths:
  /{locale}/candidate/{id}:
    get:
      summary: Retrieve a candidate information
      operationId: getResource
      parameters:
        - name: locale
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  jobTitle:
                    type: string
                  employerName:
                    type: string
                  birthDate:
                    type: string
                  address:
                    type: string
                  phoneNumber:
                    type: string
                  email:
                    type: string
                  linkedIn:
                    type: string
                  languages:
                    type: array
                    items:
                      type: string
                  distanceToWork:
                    type: integer
                  desiredSalary:
                    type: integer
                  targetSalary:
                    type: string
                  noticePeriod:
                    type: string
                  reasonForChange:
                    type: string
                  relevantExperience:
                    type: string
                  driversLicence:
                    type: boolean
                  files:
                    type: array
                    items:
                      type: string
                  statusOfCandidacy:
                    type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /{locale}/user/{id}:
    get:
      summary: Retrieve user information
      operationId: getUser
      parameters:
        - name: locale
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  canDownloadPdf:
                    type: boolean
                  canViewSalary:
                    type: boolean
                  canInvite:
                    type: boolean
                  setsTime:
                    type: boolean
                  address:
                    type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /invite/{id}:
    post:
      summary: Invite a candidate
      operationId: inviteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                duration:
                  type: integer
                channel:
                  type: string
                address:
                  type: string
                startTime:
                  type: string
      responses:
        "200":
          description: Success
        "400":
          description: Error
      security:
        - OAuth2: ["arranger"]

  /reject/{id}:
    post:
      summary: Reject a candidate
      operationId: rejectUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        "400":
          description: Error
      security:
        - OAuth2: ["arranger"]
