openapi: 3.0.0
info:
  version: "1.0"
  title: Dossier
  description: ""
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/FILIPKOWAL_1/Dossier/1.0

security:
  - OAuth2: []
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            arranger: Access to /invite and /reject endpoints

paths:
  /{locale}/candidate/{id}:
    get:
      summary: Retrieve a candidate information
      operationId: getResource
      parameters:
        - name: locale
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Christoph Kowalski
                  jobTitle:
                    type: string
                    example: Senior Consultant (CIO Advisory)
                  employerName:
                    type: string
                    example: atrete ag
                  birthDate:
                    type: string
                    example: 01.01.1990
                  address:
                    type: string
                    example: Wymyślona Street 66, Kraków
                  phoneNumber:
                    type: string
                    example: +48 666 666 666
                  email:
                    type: string
                    example: example@example.com
                  linkedIn:
                    type: string
                    example: linkedin.com/in/example
                  languages:
                    type: array
                    items:
                      type: string
                    example:
                      - Polish - native
                      - English - fluent
                      - German - basic
                  distanceToWork:
                    type: string
                    example: 5km
                  desiredSalary:
                    type: string
                    example: 130 000 CHF
                  targetSalary:
                    type: string
                    example: 100 000 CHF
                  noticePeriod:
                    type: string
                    example: 1 month
                  reasonForChange:
                    type: string
                    example: Die basenet Informatik (grösster Teil der Gruppe) wurde verkauft und viele kleinere Gesellschaften konsolidiert. Er begleitet diese 'Carve-outs' der Gesellschaften, danach ist seine Rolle obsolet bzw. nicht mehr so spannend. Er hat deshalb entschieden außerhalb der Gruppe eine neue Herausforderung zu suchen. Das Dienstleistungsportfolio von atrete tönt sehr spannend und mit den. Werten von atrete kann er sich sehr gut identifizieren.
                  relevantExperience:
                    type: string
                    example: Christoph Pfister ist seit vielen Jahren in verschiedenen Rollen im Bereich Informationstechnik unterwegs und würde sein Wissen und seine Erfahrung sehr gerne als Berater einbringen. Es reizt ihn spannende sowie komplexe Problemstellungen zu lösen und er kann dank seiner Erfahrung eine holistische Betrachtung auf Challenges einnehmen. In seiner aktuellen Rolle als CIO der PEAX AG verantwortet er die Produktentwicklung und den Betrieb einer SaaS-Plattform für digitale Services. In seiner zusätzlichen Gruppen-Rolle durfte er in der Base-Net Unternehmensgruppe verschiedene große Projekte erfolgreich umsetzen. Er ist sich gewohnt mit einer 360 Grad Sicht zu agieren und dazu die verschiedenen Sachverhalte und Themen für unterschiedliche Ziel- und Anspruchsgruppen verständlich und nachvollziehbar aufzubereiten und zu präsentieren. Als Mitglied des Enterprise Architektur Boards ist er zudem verantwortlich für die Identifikation sowie Einführung von neuen Technologien und für regulatorische und IT-rechtliche Themen.
                  driversLicence:
                    type: string
                    example: A1, B1
                  files:
                    type: array
                    items:
                      type: string
                  statusOfCandidacy:
                    description: If there's a non-empty status, front-end assumes the candidate has been invited or rejected and hides relevant action buttons.
                    type: string
                    enum:
                      - ""
                      - "We will send you an invitation once Christoph has chosen a meeting time."
                      - "We will inform you which date Christoph has chosen so that you can send him the meeting invite. Please make sure to CC: atrete@digitalent.ch to the meeting"
                      - "Please get in touch with Christoph to arrange an interview"
                      - "Iterview scheduled for ${dateTime}"
                      - "Candidate rejected"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /{locale}/user/{id}:
    get:
      summary: Retrieve user information
      operationId: getUser
      parameters:
        - name: locale
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  canDownloadPdf:
                    type: boolean
                  canViewSalary:
                    type: boolean
                  isSettingAvailibility:
                    description: False means User Case 3
                    type: boolean
                  isInviting:
                    description: True means User Case 2
                    type: boolean
                    example: false
                  address:
                    type: string
                    example: Szwajcarska 4, Kraków
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /invite/{id}:
    post:
      summary: Invite a candidate
      description: Locale is not specified as a candidate might use a different language than the user
      operationId: inviteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                duration:
                  type: integer
                channel:
                  type: string
                address:
                  type: string
                startTime:
                  type: string
      responses:
        "200":
          description: Success
        "400":
          description: Error
      security:
        - OAuth2: ["arranger"]

  /reject/{id}:
    post:
      summary: Reject a candidate
      description: Locale is not specified as a candidate might use a different language than the user
      operationId: rejectUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        "400":
          description: Error
      security:
        - OAuth2: [arranger]
