export const ml = 50;
export const mt = 71;
export const headingSize = 14;
export const textSize = 12;
export const lineHeight = 23;
export const headingLineHeight = 30;
export const maxChars = 75;
export const secondColumnXTitle = ml + 100;
export const secondColumnX = ml + 230;
